version: "2"
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/data/redis:/data

  keycluster:
    build: .
    command: app
    depends_on:
      - redis
      - postgres

    ports:
      - "50051:50051"
      - "2112:2112"